---
- name: Kubernetes bins | fetch Linux binaries to the ansible host
  synchronize:
    mode: pull
    src: "{{kubernetes_binaries_info.tmp_download_path}}/kubernetes/server/kubernetes/server/bin/{{item}}"
    dest: "{{ansible_tmp_dir}}/{{item}}"
    use_ssh_args: yes
  with_items:
    - "{{kubernetes_binaries.linux_common}}"
    - "{{kubernetes_binaries.linux_master}}"
    - "{{kubernetes_binaries.linux_minion}}"

- name: Kubernetes bins | fetch Windows binaries to the ansible host
  synchronize:
    mode: pull
    src: "{{kubernetes_binaries_info.tmp_download_path}}/kubernetes/node/bin/{{item}}"
    dest: "{{ansible_tmp_dir}}/{{item}}"
    use_ssh_args: yes
  with_items:
    - "{{kubernetes_binaries.windows}}"
